
["Common configs for The End of Herobrine Mod"]
	#Should Herobrine's and possessed creatures' eyes glow?
	eyeGlow = true
	#Should show Herobrine's nametag?
	showNametag = false
	#Should the Builder build the 1.7.10 structures?
	legacyStructures = false
	#Should possessed animals convert back?
	convertBack = true
	#Time in ticks mobs will remain possessed #Default: 1/2 minecraft day
	#Range: > 0
	remainPossessed = 12000
	#Minimum time in ticks the mod will wait to try to execute herobrine spawn logic
	#Range: > 0
	tickDelay = 600
	#Time in ticks herobrine will wait to try to spawn again
	#Range: > 0
	spawnDelay = 3600
	#The chance out of a hundred that herobrine will spawn
	#Range: 1 ~ 100
	spawnChance = 40

